/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Tony Hawks Pro Skater 3)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800A480Cu
#define func_800A480C BootEntry  /* alias */
